spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://localhost:3306/m2m_trello?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=true
    username: user01
    password: 1234

  output:
    ansi:
      enabled: ALWAYS

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml

upload:
  path: C:\\uploads


